### ISSUE TITLE
Notebooks missing

### ISSUE THREAD

**Issue by Satya21u** [justmarkham/scikit-learn-tips#1]
@justmarkham Could you please add missing tips notebooks 3, 4, 5 , 15 and 19?

**Comment by justmarkham** [comment]
Thanks for your interest! However, as mentioned in the README file:

> Note: Some of the tips do not include any code, and can only be viewed on LinkedIn.

Thus, there are no notebooks for those 5 tips. You are welcome to view those tips on LinkedIn, and participate in the discussions there or ask questions there if you like!
